const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {once}=require('node:events');
const ExcelJS=require('exceljs');
const {createApp}=require('../server');
const D=require('../domain');
test('API persistence, conflicting writers, history and report exports',async t=>{
  const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'rackmap-test-'));
  let server=createApp({dataDir});server.listen(0,'127.0.0.1');await once(server,'listening');let base=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));});
  const put=(state,revision,headers={})=>fetch(base+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({state,revision})});
  const manifestResponse=await fetch(base+'/manifest.webmanifest');
  assert.match(manifestResponse.headers.get('content-type'),/application\/manifest\+json/);
  const manifest=await manifestResponse.json();assert.equal(manifest.display,'standalone');
  for(const icon of manifest.icons){const res=await fetch(base+icon.src);assert.equal(res.status,200);const png=Buffer.from(await res.arrayBuffer());assert.equal(png.readUInt32BE(16),parseInt(icon.sizes));}
  for(const file of ['/sw.js','/pwa.js'])assert.equal((await fetch(base+file)).status,200);
  let first=await(await fetch(base+'/api/state')).json();assert.equal(first.revision,0);
  const state={schema:2,company:'Թեստ',floors:[{id:'f',name:'2-րդ հարկ',racks:[{id:'r',name:'R-01',u:12,location:'աջ դուռ',photo:'',devices:[{id:'d',name:'PP-01',type:'panel',model:'',pos:1,height:1,color:'#397c78',portList:Array.from({length:12},(_,i)=>D.port(i+1,`p${i}`))}]}]}]};
  Object.assign(state.floors[0].racks[0].devices[0].portList[0],{status:'used',cable:'=SUM(A1)',room:'205',floorId:'f',notes:'Հայերեն տեքստ',service:'camera',vlan:'20'});
  assert.equal((await put(state,0)).status,200);
  assert.equal((await put({...state,company:'Lost update'},0)).status,409);
  assert.equal((await put(state,1,{Origin:'https://untrusted.example'})).status,403);
  const invalid=structuredClone(state);invalid.floors[0].racks[0].devices[0].pos=13;assert.equal((await put(invalid,1)).status,400);
  const history=await(await fetch(base+'/api/history')).json();assert.equal(history.length,1);assert.equal((await(await fetch(base+'/api/history/0')).json()).state.company,'');
  assert.equal((await fetch(base+'/data/rackmap.sqlite')).status,404);assert.equal((await fetch(base+'/server.js')).status,404);
  const xlsx=await fetch(base+'/api/export.xlsx?query=205');assert.equal(xlsx.status,200);const book=new ExcelJS.Workbook();await book.xlsx.load(Buffer.from(await xlsx.arrayBuffer()));const sheet=book.getWorksheet('Միացումներ');assert.equal(sheet.rowCount,2);assert.equal(sheet.getCell('F2').value,'=SUM(A1)');assert.equal(sheet.getCell('L2').value,'Հայերեն տեքստ');
  assert.equal(sheet.getCell('M2').value,'Տեսախցիկ');assert.equal(sheet.getCell('N2').value,'20');
  const invalidVlan=structuredClone(state);invalidVlan.floors[0].racks[0].devices[0].portList[0].vlan='4095';assert.equal((await put(invalidVlan,1)).status,400);
  const pdf=await fetch(base+'/api/export.pdf?query=205');assert.equal(pdf.status,200);const bytes=Buffer.from(await pdf.arrayBuffer());assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.ok(bytes.length>5000);
  const pdfAll=await fetch(base+'/api/export.pdf');assert.equal(pdfAll.status,200);assert.ok((await pdfAll.arrayBuffer()).byteLength>bytes.length);
  const created=await fetch(base+'/api/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Երկրորդ ընկերություն',floorCount:3})});assert.equal(created.status,201);const second=await created.json();
  const list=await(await fetch(base+'/api/companies')).json();assert.equal(list.length,2);
  const other=await(await fetch(base+'/api/state?company='+second.id)).json();assert.equal(other.state.company,'Երկրորդ ընկերություն');assert.equal(other.state.floors.length,3);assert.equal(other.revision,0);
  other.state.company='Երկրորդի նոր անուն';assert.equal((await fetch(base+'/api/state?company='+second.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(other)})).status,200);
  assert.equal((await(await fetch(base+'/api/state')).json()).state.company,'Թեստ');
  assert.equal((await(await fetch(base+'/api/history?company='+second.id)).json()).length,1);assert.equal((await(await fetch(base+'/api/history/0?company='+second.id)).json()).state.company,'Երկրորդ ընկերություն');
  assert.equal((await fetch(base+'/api/state?company=missing')).status,404);
  const otherBook=new ExcelJS.Workbook();await otherBook.xlsx.load(Buffer.from(await(await fetch(base+'/api/export.xlsx?company='+second.id)).arrayBuffer()));assert.equal(otherBook.getWorksheet('Միացումներ').rowCount,1);
  const allBackup=await fetch(base+'/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(allBackup.status,200);const backupFile=path.join(dataDir,'downloaded.sqlite');fs.writeFileSync(backupFile,Buffer.from(await allBackup.arrayBuffer()));const {DatabaseSync}=require('node:sqlite');const snap=new DatabaseSync(backupFile,{readOnly:true});assert.equal(snap.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(snap.prepare('SELECT count(*) AS n FROM companies').get().n,2);snap.close();
  await new Promise(resolve=>server.close(resolve));server=createApp({dataDir});server.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;
  const saved=await(await fetch(base+'/api/state')).json();assert.equal(saved.revision,1);assert.equal(saved.state.company,'Թեստ');
  assert.equal((await(await fetch(base+'/api/state?company='+second.id)).json()).state.company,'Երկրորդի նոր անուն');
});
