const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {openStore,SCHEMA_VERSION}=require('../storage');
const D=require('../domain');
test('legacy database migration preserves data and history outside the source folder',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'rackmap-migration-'));
  const legacyPath=path.join(root,'legacy.sqlite');
  const legacy=new DatabaseSync(legacyPath);
  const old={...D.empty(),company:'Հին ընկերություն',floors:[{id:'f1',name:'1-ին հարկ',racks:[]}]};
  legacy.exec('CREATE TABLE project(id INTEGER PRIMARY KEY, revision INTEGER,body TEXT); CREATE TABLE history(revision INTEGER PRIMARY KEY,saved_at TEXT,body TEXT);');
  legacy.prepare('INSERT INTO project VALUES(1,7,?)').run(JSON.stringify(old));
  legacy.prepare('INSERT INTO history VALUES(6,?,?)').run('2026-09-07',JSON.stringify({...old,company:'Հին անուն'}));legacy.close();
  const original=fs.readFileSync(legacyPath);
  const dataDir=path.join(root,'separate-data');let store=openStore({dataDir,legacyPath});
  assert.equal(store.db.prepare('PRAGMA user_version').get().user_version,SCHEMA_VERSION);
  assert.deepEqual(JSON.parse(store.db.prepare("SELECT body FROM companies WHERE id='default'").get().body),old);
  assert.equal(store.db.prepare("SELECT revision FROM companies WHERE id='default'").get().revision,7);
  assert.equal(store.db.prepare("SELECT count(*) AS n FROM company_history WHERE company_id='default'").get().n,1);
  assert.deepEqual(fs.readFileSync(legacyPath),original);
  const files=fs.readdirSync(store.backups);assert.ok(files.some(x=>x.startsWith('before-schema-2-')));assert.ok(files.some(x=>x.startsWith('rackmap-')));
  const snap=new DatabaseSync(store.backup(),{readOnly:true});assert.equal(snap.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(snap.prepare('SELECT count(*) AS n FROM companies').get().n,1);snap.close();
  store.db.prepare("UPDATE companies SET revision=8,body=? WHERE id='default'").run(JSON.stringify({...old,company:'Նոր անուն'}));store.db.close();
  store=openStore({dataDir,legacyPath});assert.equal(JSON.parse(store.db.prepare("SELECT body FROM companies WHERE id='default'").get().body).company,'Նոր անուն');assert.equal(store.db.prepare("SELECT revision FROM companies WHERE id='default'").get().revision,8);store.db.close();
});
test('a newer database schema is never reset or overwritten by older code',()=>{
  const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'rackmap-newer-schema-'));
  const file=path.join(dataDir,'rackmap.sqlite'),db=new DatabaseSync(file);db.exec('PRAGMA user_version=999;CREATE TABLE precious(value TEXT);INSERT INTO precious VALUES(\'keep\');');db.close();
  assert.throws(()=>openStore({dataDir}),/newer/);const check=new DatabaseSync(file,{readOnly:true});assert.equal(check.prepare('SELECT value FROM precious').get().value,'keep');check.close();
});
