const {test}=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const {createApp}=require('../server');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {once}=require('node:events');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<100;i++){if(fn())return;await sleep(25);}throw new Error('Timed out waiting for UI');}

test('mobile navigation starts closed and opens port sheet without a modal',async t=>{
  const server=createApp({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),'rackmap-mobile-'))});server.listen(0,'127.0.0.1');await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`,D=require('../domain');
  const state={...D.empty(),company:'Mobile',floors:[{id:'f',name:'Floor',racks:[{id:'r',name:'Rack',u:6,photo:'',location:'',devices:[{id:'d',name:'Panel',type:'panel',pos:6,height:1,color:'#174e50',model:'',portList:Array.from({length:12},(_,i)=>D.port(i+1,'p'+i))}]}]}]};
  await fetch(base+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:0})});
  const dom=await JSDOM.fromURL(base,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,beforeParse(w){w.fetch=(url,options)=>fetch(new URL(url,base),options);w.structuredClone=structuredClone;w.matchMedia=q=>({matches:q.includes('max-width'),addEventListener(){}});w.scrollTo=()=>{};w.HTMLDialogElement.prototype.close=function(){this.open=false;};}});
  t.after(async()=>{dom.window.close();await new Promise(r=>server.close(r));});
  const w=dom.window,$=q=>w.document.querySelector(q);await until(()=>$('.rack-link'));
  assert.ok(w.document.body.classList.contains('left-collapsed'));assert.ok($('.mobile-nav'));
  w.location.hash='#rack/r';await until(()=>$('.mini-port'));assert.equal($('#panelBackdrop').hidden,true);
  $('.mini-port').click();await until(()=>$('#portForm'));assert.equal($('#panelBackdrop').hidden,false);assert.equal($('#dialog').open,false);
  const form=$('#portForm');$('#panelBackdrop').click();await until(()=>$('#panelBackdrop').hidden);assert.equal($('#portForm'),form);
  $('[data-action=toggle-left]').click();await until(()=>!w.document.body.classList.contains('left-collapsed'));
  $('#leftPanel a[data-view=search]').click();await until(()=>$('[data-filter=query]'));assert.equal($('#panelBackdrop').hidden,true);
});
test('full UI flow: setup, racks, devices, validation, connections, search, editing and reload',async t=>{
  const server=createApp({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),'rackmap-ui-'))});server.listen(0,'127.0.0.1');await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`;const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
  const dom=await JSDOM.fromURL(base,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.fetch=(url,opts)=>fetch(new URL(url,base),opts);w.structuredClone=structuredClone;w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};}});
  t.after(async()=>{dom.window.close();await new Promise(r=>server.close(r));});
  const w=dom.window,$=q=>w.document.querySelector(q),click=async q=>{assert.ok($(q),`Missing ${q}`);$(q).click();await sleep(15);};
  const fill=(name,value)=>{const e=$(`#dialog[open] [name="${name}"]`)||$(`#portForm [name="${name}"]`)||$(`[name="${name}"]`);assert.ok(e,`Missing field ${name}`);e.value=value;};
  const submit=async()=>{const form=$('#dialog[open] #modalForm')||$('#portForm')||$('#setupForm');form.requestSubmit(form.querySelector('button[type=submit]')||form.querySelector('button'));await sleep(25);};
  await until(()=>$('#setupForm'));fill('company','Իմ ընկերություն');fill('count',2);await submit();assert.ok($('#companyLabel').textContent.includes('Իմ ընկերություն'));
  w.location.hash='#floors';await sleep(30);await click('[data-action="rack-new"]');fill('name','R-01');fill('u',9);await submit();
  await click('.rack-link');await until(()=>$('.rack-case'));assert.equal(w.document.querySelectorAll('.rack-tick').length,9);
  await click('[data-action="device-new"]');fill('name','PP-01');fill('pos',8);fill('height',2);await submit();assert.equal(w.document.querySelectorAll('.mini-port').length,24);
  await click('[data-action="device-new"]');fill('name','SW-01');fill('type','switch');$('#type').dispatchEvent(new w.Event('change',{bubbles:true}));assert.deepEqual([...$('#count').options].map(x=>x.value),['28','48']);assert.equal($('#count').value,'28');fill('pos',8);fill('height',1);await submit();assert.match($('#formError').textContent,/զբաղված/);fill('pos',6);await submit();assert.equal(w.document.querySelectorAll('.mini-port').length,52);
  await click('.mini-port');assert.equal($('#dialog').open,false);assert.ok($('#portTools #portForm'));
  await click('[data-action=toggle-left]');assert.equal($('#leftPanel').inert,true);assert.equal($('[data-action=toggle-left]').getAttribute('aria-expanded'),'false');
  await click('[data-action=toggle-left]');assert.equal($('#leftPanel').inert,false);
  const editor=$('#portForm');
  await click('[data-action=toggle-right]');assert.equal($('#rightPanel').inert,true);
  await click('.mini-port');assert.equal($('#rightPanel').inert,false);
  await click('[data-action=toggle-right]');await click('[data-action=toggle-right]');assert.ok($('#portForm'));
  fill('cable','C-001');fill('room','205');fill('door','Աջ դուռ');fill('floorId',$('#portForm #floorId option:last-child').value);fill('switchPortId',$('#switchPortId option:nth-child(2)').value);
  await click('#portForm input[value=camera]');fill('vlan','20');await submit();assert.equal(w.document.querySelectorAll('.mini-port.used').length,2);
  assert.equal($('.mini-port').style.getPropertyValue('--port-color'),'#a65d08');assert.match($('.mini-port').title,/VLAN 20/);
  const switchPort=w.document.querySelectorAll('.mini-port.used')[1];switchPort.click();await sleep(20);assert.equal($('#dialog').open,false);assert.equal($('#vlan').value,'20');assert.equal($('#portForm input[name=service]:checked').value,'camera');
  await click('#portForm input[value=wifi]');fill('vlan','30');await submit();assert.match($('.mini-port').title,/Wi-Fi/);assert.match($('.mini-port').title,/VLAN 30/);
  fill('vlan','4095');$('#vlan').dispatchEvent(new w.Event('input',{bubbles:true}));await sleep(650);assert.equal($('#portError').hidden,false);assert.match($('.mini-port').title,/VLAN 30/);
  await click('[data-action=port-discard]');assert.equal($('#vlan').value,'30');
  await click('.mini-port.used');fill('status','fault');await submit();assert.equal(w.document.querySelectorAll('.mini-port.fault').length,1);
  w.location.hash='#search';await until(()=>$('[data-filter=query]'));$('[data-filter=query]').value='205';$('[data-filter=query]').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelectorAll('tbody tr').length,2);
  await click('tbody [data-action=port]');await until(()=>$('#portForm'));assert.equal($('#room').value,'205');assert.equal($('#dialog').open,false);await click('[data-action=port-deselect]');
  await click('[data-action=save]');await until(()=>$('#saveStatus').textContent==='Պահված է');const state=await(await fetch(base+'/api/state')).json();assert.equal(state.state.company,'Իմ ընկերություն');assert.equal(state.state.floors[0].racks[0].devices.length,2);
  await click('[data-action=company-new]');fill('name','Մյուս ընկերություն');fill('floorCount',3);await submit();await until(()=>$('#companyLabel').textContent==='Մյուս ընկերություն');
  const secondCompany=$('#companySelect').value;assert.notEqual(secondCompany,'default');assert.equal(w.document.querySelectorAll('.floor-card').length,3);assert.equal(w.document.querySelectorAll('.rack-link').length,0);
  $('#companySelect').value='default';$('#companySelect').dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>$('#companyLabel').textContent==='Իմ ընկերություն');assert.equal(w.document.querySelectorAll('.rack-link').length,1);
  w.location.hash='#settings';await until(()=>$('#networkInfo'));await click('[data-action=history]');await until(()=>$('.history-row'));await click('[data-action=close]');
  const color=$('[data-service-color=wifi]');color.value='#ffffff';color.dispatchEvent(new w.Event('change',{bubbles:true}));
  await click('[data-action=save]');await until(()=>$('#saveStatus').textContent==='Պահված է');
  assert.equal((await(await fetch(base+'/api/state')).json()).state.serviceColors.wifi,'#ffffff');
  assert.equal((await(await fetch(base+'/api/state?company='+secondCompany)).json()).state.serviceColors,undefined);
  w.location.hash='#search';await until(()=>$('[data-filter=query]'));await click('tbody [data-action=port]');
  assert.equal($('.mini-port').style.getPropertyValue('--port-color'),'#ffffff');
  assert.equal($('.mini-port').style.getPropertyValue('--port-ink'),'#10242a');
  const remote=await(await fetch(base+'/api/state')).json();remote.state.company='Այլ աշխատակցի փոփոխություն';
  assert.equal((await fetch(base+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(remote)})).status,200);
  fill('room','206');await submit();await click('[data-action=save]');await until(()=>$('#saveStatus').dataset.error==='true');
  assert.equal((await(await fetch(base+'/api/state')).json()).state.company,'Այլ աշխատակցի փոփոխություն');assert.ok(w.localStorage.getItem('rackmap-recovery-v2'));assert.equal($('#connectionBanner').hidden,false);
  assert.deepEqual(errors,[]);
});
