using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Microsoft.Win32;
namespace MyPatch;
public sealed class MapEditor:Grid {
    readonly MainWindow owner;readonly Canvas canvas=new();readonly ScrollViewer scroll=new(){HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Background=Ui.B("#d9e2e4")};readonly StackPanel list=new();readonly TextBox search=new(){Margin=new Thickness(8),ToolTip="Search"};readonly ComboBox plans;readonly ComboBox floors;
    JsonObject? plan;string selected="";double zoom=.5;Point? pan;double panX,panY;bool switching;
    public MapEditor(MainWindow owner){
        this.owner=owner;RowDefinitions.Add(new(){Height=GridLength.Auto});RowDefinitions.Add(new(){Height=new GridLength(1,GridUnitType.Star)});ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});ColumnDefinitions.Add(new(){Width=new GridLength(260)});
        plans=Ui.Select(owner.State.A("floorPlans").Objects().Select(p=>(p.S("id"),p.S("name"))),owner.MapPlanId,180);floors=Ui.Select(new[]{("","Բոլոր հարկերը")}.Concat(owner.State.A("floors").Objects().Select(f=>(f.S("id"),f.S("name")))),"",150);
        var toolbar=Ui.Bar(plans,floors,Ui.AsyncButton("Բեռնել հատակագիծ",Upload,true),Ui.Button("Խմբագրել",Edit),Ui.Button("Ջնջել",Delete),Ui.Button("−",()=>Scale(zoom/1.25)),Ui.Button("+",()=>Scale(zoom*1.25)),Ui.Button("Տեղավորել",Fit),Ui.Button("PDF / Տպել",()=>owner.PrintMaps()),Ui.AsyncButton("Կիսվել հղումով",()=>owner.Share()));Grid.SetColumnSpan(toolbar,2);Children.Add(toolbar);
        canvas.LayoutTransform=new ScaleTransform(zoom,zoom);scroll.Content=canvas;Grid.SetRow(scroll,1);Children.Add(scroll);
        var side=new DockPanel{Background=(Brush)Application.Current.Resources["Surface"],Margin=new Thickness(10,0,0,0)};var header=Ui.Stack(Ui.Text("Միացված սարքեր",18),search,Ui.Text("Ընտրեք սարքը և սեղմեք հատակագծի վրա։",12));header.Margin=new Thickness(12);DockPanel.SetDock(header,Dock.Top);side.Children.Add(header);side.Children.Add(Ui.Scroll(list));Grid.SetRow(side,1);Grid.SetColumn(side,1);Children.Add(side);
        plans.SelectionChanged+=(_,_)=>{owner.MapPlanId=Ui.Value(plans);Draw();Fit();};floors.SelectionChanged+=(_,_)=>{if(switching||plan==null)return;var id=plan.S("id");owner.Change(s=>J.Find(s,id)!["floorId"]=Ui.Value(floors),false);Draw();};search.TextChanged+=(_,_)=>DrawList();
        canvas.MouseLeftButtonDown+=(_,e)=>{if(plan==null||selected==""||e.OriginalSource is not Image)return;var at=e.GetPosition(canvas);Place(selected,at.X/canvas.Width,at.Y/canvas.Height);};
        scroll.PreviewMouseWheel+=(_,e)=>{if(Keyboard.Modifiers.HasFlag(ModifierKeys.Control)){Scale(zoom*(e.Delta>0?1.15:1/1.15));e.Handled=true;}};
        scroll.PreviewMouseRightButtonDown+=(_,e)=>{if(e.OriginalSource is Image){pan=e.GetPosition(scroll);panX=scroll.HorizontalOffset;panY=scroll.VerticalOffset;scroll.CaptureMouse();e.Handled=true;}};
        scroll.MouseMove+=(_,e)=>{if(pan is Point start){var at=e.GetPosition(scroll);scroll.ScrollToHorizontalOffset(panX+start.X-at.X);scroll.ScrollToVerticalOffset(panY+start.Y-at.Y);}};
        scroll.MouseRightButtonUp+=(_,_)=>{pan=null;scroll.ReleaseMouseCapture();};Loaded+=(_,_)=>{Draw();Fit();};
    }
    public void Draw(){
        plan=owner.State.A("floorPlans").Objects().FirstOrDefault(p=>p.S("id")==Ui.Value(plans));canvas.Children.Clear();if(plan==null){DrawList();return;}owner.MapPlanId=plan.S("id");switching=true;floors.SelectedValue=plan.S("floorId");switching=false;
        canvas.Width=plan.I("width");canvas.Height=plan.I("height");canvas.Children.Add(new Image{Source=Files.Image(plan.S("image")),Width=canvas.Width,Height=canvas.Height,Stretch=Stretch.Fill});
        var data=owner.Logic.Map(owner.State,plan.S("id"));foreach(var marker in data.A("markers").Objects()){
            var row=(JsonObject)marker["row"]!;var visual=MarkerVisual(owner.State,row,marker.I("number"),owner.Logic);var thumb=new Thumb{Width=82,Height=58,Tag=visual,ToolTip=row.S("device")+" / "+row.S("port")+" · "+row.S("room"),Cursor=Cursors.SizeAll,Template=MarkerTemplate()};
            double x=marker.D("x"),y=marker.D("y");Canvas.SetLeft(thumb,x*canvas.Width-41);Canvas.SetTop(thumb,y*canvas.Height-29);canvas.Children.Add(thumb);
            thumb.DragDelta+=(_,e)=>{Canvas.SetLeft(thumb,Math.Clamp(Canvas.GetLeft(thumb)+e.HorizontalChange,-41,canvas.Width-41));Canvas.SetTop(thumb,Math.Clamp(Canvas.GetTop(thumb)+e.VerticalChange,-29,canvas.Height-29));};
            thumb.DragCompleted+=(_,_)=>{var nx=(Canvas.GetLeft(thumb)+41)/canvas.Width;var ny=(Canvas.GetTop(thumb)+29)/canvas.Height;Place(marker.S("portId"),nx,ny);};
            var menu=new ContextMenu();var edit=new MenuItem{Header=Ui.T("Խմբագրել")};edit.Click+=(_,_)=>owner.EditPort(marker.S("portId"));menu.Items.Add(edit);var remove=new MenuItem{Header=Ui.T("Հեռացնել նշանը")};remove.Click+=(_,_)=>Remove(marker.S("portId"));menu.Items.Add(remove);thumb.ContextMenu=menu;
            thumb.KeyDown+=(_,e)=>{if(e.Key==Key.Delete){Remove(marker.S("portId"));e.Handled=true;}};thumb.Focusable=true;
        }DrawList();
    }
    static ControlTemplate MarkerTemplate(){var template=new ControlTemplate(typeof(Thumb));var f=new FrameworkElementFactory(typeof(ContentPresenter));f.SetBinding(ContentPresenter.ContentProperty,new System.Windows.Data.Binding("Tag"){RelativeSource=System.Windows.Data.RelativeSource.TemplatedParent});template.VisualTree=f;return template;}
    internal void VerifyRendered(){if(plan==null)return;var data=owner.Logic.Map(owner.State,plan.S("id"));if(canvas.Children.OfType<Thumb>().Count()!=data.A("markers").Count||list.Children.Count==0)throw new Exception("Map controls were not rendered");}
    internal void VerifyPlacement(){if(plan==null)return;var before=owner.State.ToJsonString();var data=owner.Logic.Map(owner.State,plan.S("id"));var placed=data.A("markers").Objects().Select(m=>m.S("portId")).ToHashSet();var row=data.A("devices").Objects().FirstOrDefault(r=>!placed.Contains(r["p"].S("id")));if(row==null)return;var count=list.Children.OfType<Button>().Count();var id=row["p"].S("id");Place(id,.25,.25);if(list.Children.OfType<Button>().Count()!=count-1)throw new Exception("Placed device remains selectable");Remove(id);if(list.Children.OfType<Button>().Count()!=count||owner.State.ToJsonString()!=before)throw new Exception("Marker removal did not restore the device");}
    public static UIElement MarkerVisual(JsonObject state,JsonObject row,int number,Domain logic){
        var color=state["serviceColors"]?.S(row.S("service"));if(string.IsNullOrEmpty(color))color="#147d75";var p=Ui.Stack();var geometry=logic.Call(state,"D.serviceIcon("+System.Text.Json.JsonSerializer.Serialize(row.S("service"))+")").ToString();p.Children.Add(new System.Windows.Shapes.Path{Data=Geometry.Parse(geometry),Stroke=Ui.B(color),StrokeThickness=2,Width=25,Height=25,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,0,3)});p.Children.Add(new TextBlock{Text=row.S("room") is {Length:>0} room?room:Ui.T(logic.Label(state,row.S("service")))+" "+number,TextAlignment=TextAlignment.Center,Foreground=Ui.B("#163f44"),FontSize=11,TextTrimming=TextTrimming.CharacterEllipsis});return new Border{Child=p,Padding=new Thickness(4),Background=Brushes.White,BorderBrush=Ui.B(color),BorderThickness=new Thickness(2),CornerRadius=new CornerRadius(7)};
    }
    void DrawList(){list.Children.Clear();if(plan==null)return;var data=owner.Logic.Map(owner.State,plan.S("id"));var placed=data.A("markers").Objects().Select(m=>m.S("portId")).ToHashSet();var query=search.Text.Trim();var rows=data.A("devices").Objects().Where(r=>!placed.Contains(r["p"].S("id"))&&(query==""||new[]{"floor","rack","device","port","room","cable","service","notes"}.Any(k=>r.S(k).Contains(query,StringComparison.OrdinalIgnoreCase)))).ToList();foreach(var group in rows.GroupBy(r=>r.S("service"))){list.Children.Add(Ui.Text(Ui.T(owner.Logic.Label(owner.State,group.Key))+" · "+group.Count(),16));foreach(var row in group){var id=row["p"].S("id");var b=Ui.Button((row.S("room") is {Length:>0} room?room:Ui.T(owner.Logic.Label(owner.State,row.S("service"))))+"\n"+row.S("rack")+" / "+row.S("device")+" / "+row.S("port"),()=>{selected=id;DrawList();},id==selected);b.HorizontalContentAlignment=HorizontalAlignment.Left;list.Children.Add(b);}}if(rows.Count==0)list.Children.Add(Ui.Text("Չտեղադրված սարքեր չկան։",13));}
    void Place(string portId,double x,double y){if(plan==null)return;var id=plan.S("id");owner.Change(s=>{var p=J.Find(s,id)!;var data=owner.Logic.Map(s,id);var projected=data.A("markers").Objects().FirstOrDefault(m=>m.S("portId")==portId);var m=p.A("markers").Objects().FirstOrDefault(m=>m.S("id")==projected?.S("id"));if(m==null){m=new(){["id"]=J.Id(),["portId"]=portId};p.A("markers").Add(m);}m["x"]=Math.Clamp(x,0,1);m["y"]=Math.Clamp(y,0,1);},false);selected="";Draw();}
    void Remove(string portId){if(plan==null)return;var id=plan.S("id");owner.Change(s=>{var p=J.Find(s,id)!;var alias=J.Ports(s).First(x=>x.p.S("id")==portId).p.S("switchPortId");foreach(var m in p.A("markers").Objects().Where(m=>m.S("portId")==portId||m.S("portId")==alias).ToList())p.A("markers").Remove(m);},false);Draw();}
    async Task Upload(){var dialog=new OpenFileDialog{Filter="Floor plan|*.pdf;*.png;*.jpg;*.jpeg;*.bmp"};if(dialog.ShowDialog()!=true)return;int page=1;string name=System.IO.Path.GetFileNameWithoutExtension(dialog.FileName),floor="";if(!new Form("Բեռնել հատակագիծ",v=>{name=v.S("name");floor=v.S("floor");page=v.I("page",1);}).Text("name","Անվանում",name).Choice("floor","Հարկ",new[]{("","Բոլոր հարկերը")}.Concat(owner.State.A("floors").Objects().Select(f=>(f.S("id"),f.S("name"))))).Text("page","PDF էջ","1").Run())return;var image=await Files.LoadPlan(dialog.FileName,page);var id=J.Id();owner.Change(s=>{s["floorPlans"]??=new JsonArray();s.A("floorPlans").Add(new JsonObject{["id"]=id,["name"]=name,["floorId"]=floor,["image"]=image.Data,["width"]=image.Width,["height"]=image.Height,["markers"]=new JsonArray()});},false);owner.MapPlanId=id;plans.ItemsSource=owner.State.A("floorPlans").Objects().Select(p=>new KeyValuePair<string,string>(p.S("id"),p.S("name"))).ToList();plans.SelectedValue=id;Draw();Fit();}
    void Edit(){if(plan==null)return;var id=plan.S("id");new Form("Խմբագրել հատակագիծը",v=>owner.Change(s=>J.Find(s,id)!["name"]=v.S("name"))).Text("name","Անվանում",plan.S("name")).Run();}
    void Delete(){if(plan==null||!Ui.Confirm("Ջնջե՞լ հատակագիծը և նրա նշանները։"))return;var id=plan.S("id");owner.Change(s=>s.A("floorPlans").Remove(J.Find(s,id)));}
    void Scale(double value){zoom=Math.Clamp(value,.08,4);canvas.LayoutTransform=new ScaleTransform(zoom,zoom);}
    void Fit(){if(canvas.Width>0&&scroll.ActualWidth>20)Scale((scroll.ActualWidth-24)/canvas.Width);}
}
