using System.IO;
using System.Text;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using Microsoft.Win32;
namespace MyPatch;
public partial class MainWindow {
    UIElement Reports(){
        var layout=new DockPanel();var floor=Ui.Select(new[]{("","Բոլոր հարկերը")}.Concat(state.A("floors").Objects().Select(f=>(f.S("id"),f.S("name")))));var type=Ui.Select(new[]{("","Բոլոր սարքերը")}.Concat(DeviceTypes()));var query=new TextBox{Width=220,Margin=new Thickness(0,0,8,6),ToolTip=T("Որոնում")};var grid=Ui.Table([]);
        List<JsonObject> Filter()=>domain.Rows(state).Objects().Where(r=>(Ui.Value(floor)==""||r["f"].S("id")==Ui.Value(floor)||r["p"].S("floorId")==Ui.Value(floor))&&(Ui.Value(type)==""||r.S("type")==Ui.Value(type))&&(query.Text==""||new[]{"floor","rack","device","port","room","cable","service","notes","switchName","vlan"}.Any(k=>r.S(k).Contains(query.Text,StringComparison.OrdinalIgnoreCase)))).ToList();
        void Update()=>grid.ItemsSource=Filter().Select(r=>new{Id=r["p"].S("id"),Floor=r.S("floor"),Rack=r.S("rack"),Device=r.S("device"),Port=r.S("port"),Switch=r.S("switchName"),SwitchPort=r.S("switchPort"),Purpose=T(domain.Label(state,r.S("service"))),Room=r.S("room"),Cable=r.S("cable"),Status=r.S("status"),VLAN=r.S("vlan"),Connection=r.S("connection"),Notes=r.S("notes")}).ToList();
        var controls=Ui.Stack(Ui.Text("Հաշվետվություններ",28),Ui.Bar(floor,type,query,Ui.Button("PDF / Տպել",()=>PrintTable(Filter())),Ui.Button("CSV",()=>{var dialog=new SaveFileDialog{Filter="CSV|*.csv",FileName="MyPatch-ports.csv"};if(dialog.ShowDialog()!=true)return;string[] keys=["floor","rack","device","port","switchName","switchPort","service","room","cable","status","vlan","notes"];string Cell(string v)=>"\""+((v.Length>0&&"=+-@".Contains(v[0]))?"'":"")+v.Replace("\"","\"\"")+"\"";File.WriteAllText(dialog.FileName,string.Join(',',keys)+"\r\n"+string.Join("\r\n",Filter().Select(r=>string.Join(',',keys.Select(k=>Cell(r.S(k)))))),new UTF8Encoding(true));}),Ui.Button("Սարքերի սխեմաներ",PrintMaps),Ui.AsyncButton("Կիսվել հղումով",Share)));
        DockPanel.SetDock(controls,Dock.Top);layout.Children.Add(controls);layout.Children.Add(grid);grid.AutoGeneratingColumn+=(_,e)=>{if(e.PropertyName=="Id")e.Cancel=true;};grid.MouseDoubleClick+=(_,_)=>{if(grid.SelectedItem is { } row&&row.GetType().GetProperty("Id")?.GetValue(row) is string id)EditPort(id);};floor.SelectionChanged+=(_,_)=>Update();type.SelectionChanged+=(_,_)=>Update();query.TextChanged+=(_,_)=>Update();Update();return layout;
    }
    JsonObject? ExportOptions(string title){JsonObject? options=null;new Form(title,v=>options=v).Choice("kind","Բովանդակություն",[("all","Քարտեզ և սարքերի սխեմաներ"),("maps","Քարտեզ"),("devices","Սարքերի սխեմաներ")],page=="map"?"maps":"devices").Choice("floorId","Հարկ",new[]{("","Բոլոր հարկերը")}.Concat(state.A("floors").Objects().Select(f=>(f.S("id"),f.S("name")))),J.Find(state,MapPlanId)?.S("floorId")??"").Choice("deviceType","Սարքի տեսակ",new[]{("all","Բոլոր սարքերը")}.Concat(DeviceTypes())).Choice("deviceId","Սարք",new[]{("","Բոլոր սարքերը")}.Concat(J.Devices(state).Select(x=>(x.d.S("id"),x.f.S("name")+" / "+x.r.S("name")+" / "+x.d.S("name"))))).Choice("planId","Հատակագիծ",new[]{("","Բոլոր հատակագծերը")}.Concat(state.A("floorPlans").Objects().Select(p=>(p.S("id"),p.S("name")))),page=="map"?MapPlanId:"").Choice("language","Լեզու",[("hy","Հայերեն"),("en","English"),("ru","Русский")],language).Choice("days","Հղման ժամկետ",[("7","7 օր"),("30","30 օր"),("90","90 օր")],"30").Run();return options;}
    public void PrintMaps(){var options=ExportOptions("PDF / Տպել");if(options==null)return;var document=MakeDocument(options);if(document.Pages.Count==0)throw new Exception(T("Ընտրված պայմաններով տվյալներ չկան"));var file=new SaveFileDialog{Filter="PDF|*.pdf",FileName=SafeName(state.S("company"))+".pdf"};if(file.ShowDialog()==true){PdfExport.Save(document.DocumentPaginator,file.FileName);Status("PDF · "+file.FileName);}}
    FixedDocument MakeDocument(JsonObject options){
        var doc=new FixedDocument();var outputLanguage=options.S("language");string L(string text)=>domain.Translate(text,outputLanguage);var snapshot=state.Copy();
        void Page(string title,UIElement content){var page=new FixedPage{Width=1122,Height=794,Background=Brushes.White};var heading=new TextBlock{Text=snapshot.S("company"),FontFamily=new FontFamily("Segoe UI"),FontSize=24,Foreground=Ui.B("#193e44")};FixedPage.SetLeft(heading,36);FixedPage.SetTop(heading,24);page.Children.Add(heading);var sub=new TextBlock{Text=title,FontSize=15,Foreground=Ui.B("#147d75")};FixedPage.SetLeft(sub,36);FixedPage.SetTop(sub,64);page.Children.Add(sub);if(content is FrameworkElement element){element.Width=1050;element.Height=620;}FixedPage.SetLeft(content,36);FixedPage.SetTop(content,108);page.Children.Add(content);var footer=new TextBlock{Text="My Patch · "+DateTime.Now.ToString("yyyy-MM-dd")+" · "+(doc.Pages.Count+1),FontSize=10};FixedPage.SetLeft(footer,36);FixedPage.SetTop(footer,765);page.Children.Add(footer);var pc=new PageContent();((System.Windows.Markup.IAddChild)pc).AddChild(page);doc.Pages.Add(pc);}
        var maps=snapshot.A("floorPlans").Objects().Where(p=>(options.S("planId")==""||p.S("id")==options.S("planId"))&&(options.S("floorId")==""||p.S("floorId")==options.S("floorId")));
        bool DeviceMatches(JsonObject d)=>(options.S("deviceType")=="all"||options.S("deviceType")==d.S("type"))&&(options.S("deviceId")==""||options.S("deviceId")==d.S("id"));
        if(options.S("kind")!="devices")foreach(var plan in maps){var canvas=new Canvas{Width=plan.I("width"),Height=plan.I("height")};canvas.Children.Add(new Image{Source=Files.Image(plan.S("image")),Width=canvas.Width,Height=canvas.Height});var data=domain.Map(snapshot,plan.S("id"));foreach(var marker in data.A("markers").Objects()){
            var row=(JsonObject)marker["row"]!;var peer=J.Ports(snapshot).FirstOrDefault(x=>x.p.S("id")==row["p"].S("switchPortId"));if(!DeviceMatches((JsonObject)row["d"]!)&&(peer.d==null||!DeviceMatches(peer.d)))continue;var visual=(FrameworkElement)MapEditor.MarkerVisual(snapshot,row,marker.I("number"),domain);visual.Width=82;visual.Height=58;Canvas.SetLeft(visual,marker.D("x")*canvas.Width-41);Canvas.SetTop(visual,marker.D("y")*canvas.Height-29);canvas.Children.Add(visual);
        }Page(L("Քարտեզ")+" · "+plan.S("name")+" · "+(J.Find(snapshot,plan.S("floorId"))?.S("name")??L("Բոլոր հարկերը")),new Viewbox{Child=canvas,Stretch=Stretch.Uniform});}
        if(options.S("kind")!="maps")foreach(var x in J.Devices(snapshot).Where(x=>(options.S("floorId")==""||x.f.S("id")==options.S("floorId"))&&DeviceMatches(x.d))){Page(L("Սարքերի սխեմաներ")+" · "+x.f.S("name")+" / "+x.r.S("name")+" / "+x.d.S("name"),Ui.Stack(new TextBlock{Text=x.d.S("model"),FontSize=18,Margin=new Thickness(0,0,0,20)},PortFace(x.d,false)));
            var rows=domain.Rows(snapshot).Objects().Where(r=>r["d"].S("id")==x.d.S("id")).ToList();foreach(var chunk in rows.Chunk(18)){var stack=new StackPanel();foreach(var r in chunk)stack.Children.Add(new TextBlock{Text=r.S("port").PadLeft(2)+"    "+L(domain.Label(snapshot,r.S("service")))+"    "+r.S("room")+"    "+r.S("cable")+"    "+r.S("connection"),FontSize=13,Foreground=Ui.B("#193e44"),Margin=new Thickness(0,0,0,12)});Page(x.f.S("name")+" / "+x.r.S("name")+" / "+x.d.S("name"),stack);}
        }return doc;
    }
    void PrintTable(List<JsonObject> rows){var document=new FlowDocument{PageWidth=1122,PageHeight=794,PagePadding=new Thickness(35),ColumnWidth=1050,FontFamily=new FontFamily("Segoe UI"),FontSize=10};document.Blocks.Add(new Paragraph(new Run(state.S("company"))){FontSize=22});var table=new Table();string[] keys=["floor","rack","device","port","switchName","switchPort","service","room","cable","status"];foreach(var key in keys)table.Columns.Add(new TableColumn{Width=new GridLength(key=="port"?40:100)});var group=new TableRowGroup();table.RowGroups.Add(group);var header=new TableRow();foreach(var key in keys)header.Cells.Add(new TableCell(new Paragraph(new Run(key))){FontWeight=FontWeights.Bold});group.Rows.Add(header);foreach(var row in rows){var r=new TableRow();foreach(var key in keys)r.Cells.Add(new TableCell(new Paragraph(new Run(row.S(key)))){BorderBrush=Brushes.LightGray,BorderThickness=new Thickness(0,0,0,1)});group.Rows.Add(r);}document.Blocks.Add(table);var print=new PrintDialog();if(print.ShowDialog()==true)print.PrintDocument(((IDocumentPaginatorSource)document).DocumentPaginator,"My Patch");}
    public async Task Share(){if(project==null||project.Scope=="local"||cloud.Scope!=project.Scope)throw new Exception(T("Հղումով կիսվելու համար բացեք նախագիծը կայքի cloud-ից"));var options=ExportOptions("Կիսվել հղումով");if(options==null)return;await Sync(true);if(project.Dirty||conflicted)throw new Exception(T("Նախ պահպանեք փոփոխությունները"));options["days"]=options.I("days");options["revision"]=project.Revision;if(options.S("kind")=="devices")options["planId"]="";await cloud.Send("/api/shares","POST",options,project.RemoteId);await ManageLinks();}
    async Task ManageLinks(){if(project==null||project.Scope=="local")throw new Exception("Cloud project required");var links=(JsonArray)await cloud.Send("/api/shares",company:project.RemoteId);var window=new Window{Title=T("Իմ հղումները"),Owner=this,Width=650,Height=650,WindowStartupLocation=WindowStartupLocation.CenterOwner};var panel=new StackPanel{Margin=new Thickness(20)};foreach(var link in links.Objects()){var url="https://patch.ditaknet.com/share.html#"+link.S("token");panel.Children.Add(Ui.Card(Ui.Stack(Ui.Text(link.S("title"),16),new TextBox{Text=url,IsReadOnly=true},Ui.Bar(Ui.Button("Պատճենել հղումը",()=>Clipboard.SetText(url)),Ui.AsyncButton("Անջատել հղումը",async()=>{await cloud.Send("/api/shares/revoke","POST",new(){["token"]=link.S("token")},project.RemoteId);window.Close();await ManageLinks();})))));}window.Content=Ui.Scroll(panel);window.ShowDialog();}
}
