using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
namespace MyPatch;
public partial class MainWindow {
    internal string MapPlanId="";
    UIElement Networks(){var panel=Ui.Stack(Ui.Text("Ցանցեր և VLAN",28),Ui.Button("Ավելացնել ցանց",()=>EditNetwork(null),true));foreach(var n in state.A("networks").Objects()){
        var card=Ui.Stack(Ui.Text(n.S("name")+" · VLAN "+n.S("vlan"),20),Ui.Text(n["ip"] is JsonArray a?string.Join(", ",a.Select(x=>x?.ToString())):n.S("ip")),Ui.Bar(Ui.Button("Խմբագրել",()=>EditNetwork(n)),Ui.Button("Ավելացնել IP",()=>EditHost(n,null)),Ui.Button("Ջնջել",()=>{if(Ui.Confirm("Ջնջե՞լ ցանցը։"))Change(s=>s.A("networks").Remove(J.Find(s,n.S("id"))));})));
        foreach(var host in n.A("hosts").Objects())card.Children.Add(Ui.Bar(Ui.Text(host.S("name")+" · "+host.S("ip")+" · "+host.S("username")),Ui.Button("Խմբագրել",()=>EditHost(n,host)),Ui.Button("Ջնջել",()=>{if(Ui.Confirm("Ջնջե՞լ IP գրառումը։"))Change(s=>{var list=J.Find(s,n.S("id"))!.A("hosts");list.Remove(list.Objects().First(x=>x.S("id")==host.S("id")));});})));panel.Children.Add(Ui.Card(card));}return Ui.Scroll(panel);}
    void EditNetwork(JsonObject? network){new Form("Ցանց",v=>Change(s=>{var n=network==null?new JsonObject{["id"]=J.Id(),["hosts"]=new JsonArray()}:J.Find(s,network.S("id"))!;foreach(var key in new[]{"name","vlan"})n[key]=v.S(key);var addresses=v.S("ip").Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);n["ip"]=addresses.Length>1?new JsonArray(addresses.Select(x=>JsonValue.Create(x) as JsonNode).ToArray()):JsonValue.Create(v.S("ip"));if(network==null){s["networks"]??=new JsonArray();s.A("networks").Add(n);}})).Text("name","Անվանում",network?.S("name")??"").Text("vlan","VLAN ID",network?.S("vlan")??"").Text("ip","IP / CIDR (բաժանեք ստորակետով)",network?["ip"] is JsonArray ips?string.Join(", ",ips.Select(x=>x?.ToString())):network?.S("ip")??"").Run();}
    void EditHost(JsonObject network,JsonObject? host){new Form("IP հասցե",v=>Change(s=>{var hosts=J.Find(s,network.S("id"))!.A("hosts");var h=host==null?new JsonObject{["id"]=J.Id()}:hosts.Objects().First(x=>x.S("id")==host.S("id"));foreach(var key in new[]{"name","ip","username","password","deviceId"})h[key]=v.S(key);if(host==null)hosts.Add(h);})).Text("name","Անվանում",host?.S("name")??"").Text("ip","IP",host?.S("ip")??"").Text("username","Մուտքանուն",host?.S("username")??"").Text("password","Գաղտնաբառ",host?.S("password")??"",true).Choice("deviceId","Սարք",new[]{("","—")}.Concat(J.Devices(state).Select(x=>(x.d.S("id"),x.r.S("name")+" / "+x.d.S("name")))),host?.S("deviceId")??"").Run();}
    UIElement Settings(){
        var tabs=new TabControl();var general=Ui.Stack(Ui.Text("Կարգավորումներ",26),Ui.Text("My Patch Native · 0.1.0",14),Ui.Text("Windows / WPF · SQLite",14));
        var lang=Ui.Select([("hy","Հայերեն"),("en","English"),("ru","Русский")],language);lang.SelectionChanged+=(_,_)=>{language=Ui.Value(lang);db.SettingSave("language",language);Render();};general.Children.Add(Ui.Bar(lang,Ui.Button("Գիշեր / Ցերեկ",()=>{var dark=db.Setting("dark")!="true";db.SettingSave("dark",dark?"true":"false");Ui.Theme(dark);Background=(System.Windows.Media.Brush)Application.Current.Resources["Background"];Foreground=(System.Windows.Media.Brush)Application.Current.Resources["Ink"];Render();})));
        general.Children.Add(Ui.Card(Ui.Stack(Ui.Text("Տեղային բազա",20),Ui.Text(db.Directory),Ui.Button("Բազայի պահուստային պատճեն",()=>{var file=new SaveFileDialog{Filter="SQLite|*.sqlite",FileName="MyPatch-native-backup.sqlite"};if(file.ShowDialog()==true)db.Backup(file.FileName);}),Ui.Button("Պատմություն",History),Ui.Button("Վերանվանել նախագիծը",()=>new Form("Նախագիծ",v=>Change(s=>s["company"]=v.S("name"))).Text("name","Անվանում",state.S("company")).Run()))));
        general.Children.Add(Ui.Card(Ui.Stack(Ui.Text("Cloud",20),Ui.Text(cloud.Scope==""?"Միացած չէ":cloud.Scope),Ui.AsyncButton("Մուտք գործել",Login),Ui.AsyncButton("Համաժամացնել",()=>Sync(true)),Ui.AsyncButton("Տեղային նախագիծը պատճենել cloud",PublishProject),Ui.AsyncButton("Դուրս գալ",Logout),Ui.Button("Պահպանել որպես տեղային պատճեն",()=>{var key=J.Id();db.Put(key,state.Copy());RefreshProjects(key);}))));
        tabs.Items.Add(new TabItem{Header=T("Ընդհանուր"),Content=Ui.Scroll(general)});
        var styles=Ui.Stack(Ui.Text("Անվանումներ և գույներ",24),Ui.Button("Ավելացնել տեսակ",()=>EditService(null),true));foreach(var (id,name) in Services())styles.Children.Add(Ui.Bar(Ui.Text(name,16),Ui.Button("Խմբագրել",()=>EditService(id)),Ui.Button("Ջնջել",()=>DeleteService(id))));
        foreach(var key in new[]{"free","used","fault"})styles.Children.Add(Ui.Button(T(key switch{"used"=>"Զբաղված","fault"=>"Անսարք",_=>"Ազատ"})+" · "+T("Խմբագրել"),()=>new Form("Վիճակ",v=>Change(s=>{s["statusLabels"]??=new JsonObject();s["statusColors"]??=new JsonObject();if(v.S("name")=="")s["statusLabels"]!.AsObject().Remove(key);else s["statusLabels"]![key]=v.S("name");s["statusColors"]![key]=v.S("color");})).Text("name","Անվանում",state["statusLabels"]?.S(key)??"").Text("color","Գույն",state["statusColors"]?.S(key) is {Length:>0} c?c:"#147d75").Run()));
        tabs.Items.Add(new TabItem{Header=T("Անվանումներ և գույներ"),Content=Ui.Scroll(styles)});
        tabs.Items.Add(new TabItem{Header=T("PIN օգտատերեր"),Content=Ui.Stack(Ui.Text("PIN օգտատերեր",24),Ui.Text("Հասանելի է թիմի գլխավոր PIN-ով մուտք գործելուց հետո։"),Ui.AsyncButton("Բացել օգտատերերին",ManagePins),Ui.AsyncButton("Իմ հղումները",ManageLinks))});return tabs;
    }
    void History(){if(project==null)return;var history=db.History(project.Key);var items=history.Select(x=>(x.Id.ToString(),x.Date)).ToList();if(items.Count==0)return;new Form("Պատմություն",v=>{if(Ui.Confirm("Վերականգնե՞լ ընտրված տարբերակը։ Ընթացիկ տարբերակը կմնա պատմության մեջ։")){var old=db.Version(long.Parse(v.S("id")));domain.Validate(old);undo.Push(state.Copy());SaveState(old);Render();}}).Choice("id","Տարբերակ",items).Run();}
    void EditService(string? id){var name=id==null?"":domain.Label(state,id);var color=id==null?"#147d75":state["serviceColors"]?.S(id) is {Length:>0} c?c:state.A("serviceTypes").Objects().FirstOrDefault(x=>x.S("id")==id)?.S("color")??"#147d75";new Form("Սարքի նշանակություն",v=>Change(s=>{if(id==null){s["serviceTypes"]??=new JsonArray();s.A("serviceTypes").Add(new JsonObject{["id"]="custom-"+J.Id(),["name"]=v.S("name"),["color"]=v.S("color")});}else{var type=s.A("serviceTypes").Objects().FirstOrDefault(x=>x.S("id")==id);if(type!=null){type["name"]=v.S("name");type["color"]=v.S("color");}else{s["serviceLabels"]??=new JsonObject();s["serviceColors"]??=new JsonObject();s["serviceLabels"]![id]=v.S("name");s["serviceColors"]![id]=v.S("color");}}})).Text("name","Անվանում",name).Text("color","Գույն",color).Run();}
    void DeleteService(string id){if(id=="")throw new Exception("Չնշված տեսակը չի ջնջվում");if(J.Ports(state).Any(x=>x.p.S("service")==id))throw new Exception("Տեսակն օգտագործվում է պորտերում");if(!Ui.Confirm("Ջնջե՞լ տեսակը։"))return;Change(s=>{var custom=s.A("serviceTypes").Objects().FirstOrDefault(x=>x.S("id")==id);if(custom!=null)s.A("serviceTypes").Remove(custom);else{s["hiddenServices"]??=new JsonArray();s.A("hiddenServices").Add(id);}s["serviceLabels"]?.AsObject().Remove(id);s["serviceColors"]?.AsObject().Remove(id);});}
    async Task PublishProject(){if(project?.Scope!="local"||cloud.Scope=="")throw new Exception("Մուտք գործեք cloud և ընտրեք տեղային նախագիծը");if(!Ui.Confirm("Ստեղծե՞լ նախագծի նոր պատճենը cloud-ում։"))return;var created=await cloud.Send("/api/companies","POST",new(){["name"]=state.S("company"),["floorCount"]=1});var result=await cloud.Send("/api/state","PUT",new(){["revision"]=created.I("revision"),["state"]=state.DeepClone()},created.S("id"));var key=cloud.Scope+":"+created.S("id");db.Put(key,state,cloud.Scope,created.S("id"),result.I("revision"));RefreshProjects(key);StartPresence();}
    async Task ManagePins(){var pins=(JsonArray)await cloud.Send("/api/pins");var companyList=(JsonArray)await cloud.Send("/api/companies");var window=new Window{Title=T("PIN օգտատերեր"),Owner=this,Width=650,Height=650,WindowStartupLocation=WindowStartupLocation.CenterOwner};var rows=Ui.Stack();rows.Margin=new Thickness(18);window.Content=Ui.Scroll(rows);
        async Task SavePin(JsonObject values,JsonObject? pin){var ids=new JsonArray(values.S("projects").Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(x=>JsonValue.Create(x) as JsonNode).ToArray());var body=new JsonObject{["label"]=values.S("label"),["companyIds"]=ids,["enabled"]=values.S("enabled")=="true",["rotate"]=values.S("rotate")=="true"};if(pin!=null)body["id"]=pin.S("id");var result=await cloud.Send("/api/pins",pin==null?"POST":"PUT",body);if(result.S("pin")!="")MessageBox.Show(result.S("pin"),"PIN");window.Close();await ManagePins();}
        void Edit(JsonObject? pin){JsonObject? values=null;var form=new Form("PIN",v=>values=v).Text("label","Անվանում",pin?.S("label")??"").Checklist("projects","Հասանելի նախագծեր",companyList.Objects().Select(c=>(c.S("id"),c.S("name"))),pin==null?[]:pin.A("companyIds").Select(x=>x?.ToString()??"")).Check("enabled","Ակտիվ է",pin?["enabled"]?.GetValue<bool>()??true).Check("rotate","Ստեղծել նոր PIN",false);form.Owner=window;if(form.Run())_ = RunSafe(()=>SavePin(values!,pin));}
        rows.Children.Add(Ui.Button("Ավելացնել PIN",()=>Edit(null),true));foreach(var pin in pins.Objects())rows.Children.Add(Ui.Card(Ui.Bar(Ui.Text(pin.S("label")+" · "+pin.S("role")),Ui.Button("Խմբագրել",()=>Edit(pin)),Ui.AsyncButton("Ջնջել",async()=>{if(!Ui.Confirm("Ջնջե՞լ PIN-ը։"))return;await cloud.Send("/api/pins","DELETE",new(){["id"]=pin.S("id")});window.Close();await ManagePins();}))));window.ShowDialog();}
    static async Task RunSafe(Func<Task> action){try{await action();}catch(Exception e){Ui.Error(e);}}
}
